openapi: 3.0.0
info:
  title: Never Alone RESTful API
  description: API documentation using Swagger
  version: 1.0.0

tags:
  - name: Contacts
    description: Endpoints for managing user contacts

paths: {}
