openapi: 3.0.0
info:
  title: Never Alone RESTful API
  description: API documentation using Swagger
  version: 1.0.0

tags:
  - name: Reports
    description: Endpoints for managing reports
  - name: Contacts
    description: Endpoints for managing user contacts
  - name: Auth
    description: Endpoints for handling user authentication and account management
  - name: Community
    description: Endpoints for handling communityposts and comments

paths: {}
